version: "3"
services:
  sabzum-backend:
    container_name: sabzum-backend
    build: .
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: sabzumdb
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "4100:4100"
    networks:
      - postgres_pgnet

networks:
  postgres_pgnet:
    external: true